# Name of the automated workflow
name: DEBUG - Discover GFW Datasets

# Controls when the action runs
on:
  workflow_dispatch:

# Defines the jobs that will run
jobs:
  # This job will connect to the GFW API and list available datasets
  discover-gfw-datasets:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install requests

      - name: Create GFW Discovery script
        run: |
          cat > discover_script.py <<EOF
          import requests
          import os
          import json

          print("--- Starting GFW Dataset Discovery ---")

          api_key = os.getenv('GFW_API_KEY')
          if not api_key:
              print("!!! ERROR: GFW_API_KEY not found in secrets.")
              exit(1)
          
          url = "https://gateway.api.globalfishingwatch.org/v2/datasets"
          headers = { 'Authorization': f"Bearer {api_key}" }
          
          print(f"Requesting URL: {url}")

          try:
              response = requests.get(url, headers=headers)
              response.raise_for_status() 
              
              print("Request successful. Parsing dataset list...")
              datasets = response.json()
              
              print("\n\n--- Available Datasets ---")
              print(json.dumps(datasets, indent=2))
              print("--------------------------\n\n")

          except requests.exceptions.HTTPError as e:
              print("!!! ERROR: Request Failed !!!")
              print(f"Status Code: {e.response.status_code}")
              print("--- Server Response Body ---")
              print(e.response.text)
              print("--------------------------")
              raise e

          print("--- GFW Dataset Discovery Complete ---")
          EOF

      - name: Run GFW Discovery script
        env:
          GFW_API_KEY: ${{ secrets.GFW_API_KEY }}
        run: python discover_script.py
