# Name of the automated workflow
name: Fetch Ocean Data

# Controls when the action runs
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *' # Runs at 5 AM UTC daily

# Defines the jobs that will run
jobs:
  # First job: Fetch data from Global Fishing Watch
  fetch-gfw-data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install requests

      - name: Create GFW Python script
        run: |
          cat > gfw_script.py <<EOF
          import requests
          import os
          import json
          from datetime import datetime, date, timedelta

          print("--- Starting GFW Data Fetch using Events API v3 ---")
          api_key = os.getenv('GFW_API_KEY')
          
          # FINAL DATE LOGIC: Fetch a 3-day window ending 3 days ago for fresh, reliable data.
          end_date = datetime.utcnow().date() - timedelta(days=3)
          start_date = end_date - timedelta(days=3)
          start_date_str = start_date.strftime('%Y-%m-%d')
          end_date_str = end_date.strftime('%Y-%m-%d')
          
          print(f"Fetching data from {start_date_str} to {end_date_str}")
          
          url = "https://gateway.api.globalfishingwatch.org/v3/events"
          headers = { 'Authorization': f"Bearer {api_key}" }
          params = {
              'datasets[0]': 'public-global-fishing-events:latest',
              'types[0]': 'FISHING',
              'start-date': start_date_str,
              'end-date': end_date_str,
              'limit': 10000, # Maximize events per request
              'offset': 0
          }
          
          try:
              response = requests.get(url, headers=headers, params=params)
              response.raise_for_status() 
              
              print("Request successful. Writing to file...")
              with open("fishing_events.geojson", "w") as f:
                  f.write(response.text)

              data = response.json()
              event_count = data.get('total', 0)
              print(f"Successfully saved {event_count} events to fishing_events.geojson")
          except requests.exceptions.HTTPError as e:
              print(f"!!! ERROR: Request Failed. Status Code: {e.response.status_code}")
              print(f"--- Server Response Body ---\n{e.response.text}\n--------------------------")
              raise e
          print("--- GFW Data Fetch Complete ---")
          EOF

      - name: Run GFW script
        env:
          GFW_API_KEY: ${{ secrets.GFW_API_KEY }}
        run: python gfw_script.py
        
      - name: Commit and push if it changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated update of GFW fishing events"
          file_pattern: "fishing_events.geojson"

  # Second job: Fetch data from the ArcGIS Marine Species layer
  fetch-biodiversity-data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install requests
      - name: Create Biodiversity Python script
        run: |
          cat > biodiversity_script.py <<EOF
          import requests
          url = "https://services9.arcgis.com/IkktFdUAcY3WrH25/arcgis/rest/services/Global_Marine_Species_Patterns_(55km)/FeatureServer/0/query?where=1%3D1&outFields=Rich_all&outSR=4326&f=geojson"
          response = requests.get(url)
          response.raise_for_status()
          with open("biodiversity_richness.geojson", "w") as f:
              f.write(response.text)
          print("Successfully fetched biodiversity data and saved to biodiversity_richness.geojson")
          EOF
      - name: Run Biodiversity script
        run: python biodiversity_script.py
      - name: Commit and push if it changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated update of marine biodiversity data"
          file_pattern: "biodiversity_richness.geojson"
