# Name of the automated workflow
name: Fetch Ocean Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'

jobs:
  # This workflow now ONLY fetches GFW data.
  fetch-gfw-data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install requests
      - name: Create GFW Python script
        run: |
          cat > gfw_script.py <<EOF
          # ... (The full, working GFW Python script goes here) ...
          EOF
      - name: Run GFW script
        env:
          GFW_API_KEY: ${{ secrets.GFW_API_KEY }}
        run: python gfw_script.py
      - name: Commit and push if it changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated update of GFW fishing events"
          file_pattern: "fishing_events.geojson"
